### PR TITLE
Replaced Vector in Grid with FxHashMap

### PR DESCRIPTION
**Pull request by ghost**
now I a solid 60 fps with a grid size of 800 while previously i would only get between 20 and 25. ~~Most of the performance issues seem to be with the transform of the `Color` to  `u8` further performance improvements could be made by storing the result in the Particle itself.~~ I implemented this and now getting between 50 and 60 fps is possible at a size of 2000 with drops to 40 when the grid reaches around 40% full

### CODE REVIEW

**Comment by dmitriy-shmilo** [comment]
Amazing change. Thank you very much for the input!

**Comment by ghost** [comment]
the reason i closed this is because i came up with a much better idea. Rather than caching the colour in the hashmap any method on the grid which could mutate itself takes the texture and directly modifies the texture . Right now ill just store the texture in the Grid and the in the render system ill just copy one texture onto the other.

**Comment by dmitriy-shmilo** [comment]
Crap, I didn't notice your comment before merging, sorry.

**Comment by ghost** [comment]
I just created a new pull request with the changes i specified in my previous comment. I should have made that comment right after closing this sorry.

**Comment by dmitriy-shmilo** [comment]
Sorry for the confusion, I should've asked before re-opening this PR.

**Pull request merged**
